// Reads the real colour tokens from src/styles.css and measures every text/background pair the UI uses. Writes ../CONTRAST.md.
import fs from 'node:fs';
const css = fs.readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const block = (sel) => { const i = css.indexOf(sel + ' {'); const body = css.slice(css.indexOf('{', i) + 1, css.indexOf('\n}', i)); const t = {}; for (const m of body.matchAll(/--([a-z0-9-]+):\s*(#[0-9a-fA-F]{6})\s*;/g)) t[m[1]] = m[2]; return t; };
const themes = { Light: block(":root, :root[data-theme='light']"), Dark: block(":root[data-theme='dark']") };
const lum = (h) => { const [r, g, b] = [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255).map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)); return 0.2126 * r + 0.7152 * g + 0.0722 * b; };
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };
// [label, fg, bg, minimum]. Body copy is 17px (13pt) so it needs 4.5. Bold labels at 18pt or more would need 3; none are relied on.
const PAIRS = [
  ['Body text on page', 'text', 'bg'], ['Body text on panel', 'text', 'surface'], ['Secondary text on panel', 'text-2', 'surface'], ['Secondary text on page', 'text-2', 'bg'],
  ['Muted text on panel', 'muted', 'surface'], ['Muted text on page', 'muted', 'bg'], ['Muted text on raised panel', 'muted', 'surface-2'],
  ['Accent link on panel', 'accent', 'surface'], ['Primary button text', 'on-accent', 'accent'], ['Text on accent wash', 'text', 'accent-wash'],
  ['Amber text on amber wash', 'amber-ink', 'amber-wash'], ['Amber text on panel', 'amber-ink', 'surface'], ['Red text on red wash', 'red-ink', 'red-wash'], ['Red text on panel', 'red-ink', 'surface'],
  ['On-track block text', 'blk-ok-text', 'blk-ok'], ['Near-breach block text', 'blk-tight-text', 'blk-tight'], ['Breach-risk block text', 'blk-breach-text', 'blk-breach'],
  ['Response-sent block text', 'blk-sent-text', 'blk-sent'], ['Off-shift label', 'off-text', 'off-bg'], ['Evidence "Ready" label on raised panel', 'accent', 'surface-2'],
  ['Evidence "Requested" label on raised panel', 'amber-ink', 'surface-2'], ['Evidence "Missing" label on raised panel', 'red-ink', 'surface-2'],
  ['Focus ring against panel (3:1 non-text)', 'focus', 'surface', 3], ['Deadline line against panel (3:1 non-text)', 'amber', 'surface', 3, true],
];
let md = '# Contrast report\n\nGenerated by `npm run contrast` in `web/` from the hex tokens in `src/styles.css`. Text pairs need 4.5:1 (body copy is 17px, 13pt). Non-text marks need 3:1.\n';
let fail = 0;
for (const [name, t] of Object.entries(themes)) {
  md += `\n## ${name} theme\n\n| Pair | Foreground | Background | Ratio | Needs | Result |\n|---|---|---|---|---|---|\n`;
  for (const [label, fg, bg, min = 4.5, informational] of PAIRS) {
    const r = ratio(t[fg], t[bg]);
    const ok = r >= min;
    if (!ok && !informational) fail++;
    md += `| ${label} | ${fg} ${t[fg]} | ${bg} ${t[bg]} | ${r.toFixed(2)}:1 | ${min}:1 | ${ok ? 'pass' : informational ? 'low, backed by an outline and a word' : 'FAIL'} |\n`;
  }
}
fs.writeFileSync(new URL('../../CONTRAST.md', import.meta.url), md);
console.log(md.split('\n').filter((l) => /FAIL|low,/.test(l)).join('\n') || 'all pairs pass');
process.exit(fail ? 1 : 0);
